# Use an official KrakenD base image
FROM devopsfaith/krakend

# Set the working directory inside the container
WORKDIR /app

COPY config/krakend.tmpl /app/krakend.tmpl
ADD codefly/builder/settings /app/settings

# Set environment variables
ENV FC_ENABLE=1
ENV FC_SETTINGS="/app/settings"

# Expose the port KrakenD runs on
EXPOSE 8080

# Command to run KrakenD
CMD ["krakend", "run", "-c", "/app/krakend.tmpl"]
