name: GoReleaser

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    uses: codefly-dev/core/.github/workflows/go-service-release.yml@main
    secrets:
      GH_PAT: ${{ secrets.GITHUB_TOKEN }}
